package org.javakontor.sherlog.application.extender.internal;

public class ActionSpecification {

  private String _id;

  private String _actionGroupId;

  private String _label;

  private String _shortcut;

  private String _actionClass;

  public String getId() {
    return _id;
  }

  public void setId(String id) {
    _id = id;
  }

  public String getActionGroupId() {
    return _actionGroupId;
  }

  public void setActionGroupId(String actionGroupId) {
    _actionGroupId = actionGroupId;
  }

  public String getLabel() {
    return _label;
  }

  public void setLabel(String label) {
    _label = label;
  }

  public String getShortcut() {
    return _shortcut;
  }

  public void setShortcut(String shortcut) {
    _shortcut = shortcut;
  }

  public String getActionClass() {
    return _actionClass;
  }

  public void setActionClass(String actionClass) {
    _actionClass = actionClass;
  }

  /**
   * @generated by CodeSugar http://sourceforge.net/projects/codesugar */

  public String toString() {
    StringBuffer buffer = new StringBuffer();
    buffer.append("[Action:");
    buffer.append(" _id: ");
    buffer.append(_id);
    buffer.append(" _actionGroupId: ");
    buffer.append(_actionGroupId);
    buffer.append(" _label: ");
    buffer.append(_label);
    buffer.append(" _shortcut: ");
    buffer.append(_shortcut);
    buffer.append(" _actionClass: ");
    buffer.append(_actionClass);
    buffer.append("]");
    return buffer.toString();
  }
}
